### ISSUE TITLE
Do not call `LoadPackage( "singular", ... )' in the package file

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/corelg#6]
A warning is detected by `make testpackagesload`. Indeed, you do this:

https://github.com/gap-packages/corelg/blob/fd5b40f58b50b0c637640ea688b14e5069fdcd25/gap/realtheta.gi#L1

A proper way of doing this is to add Singular to suggested packages, and use `IsPackageMarkedForLoading` to determine whether to read `realtheta.gi` or not.

**Comment by fingolfin** [comment]
This was fixed in 9e2be5f274a98b6c812f54ad3eefcf8e2844eab3 which is in version 1.53 of this package :-)
